language: node_js
node_js: '7.0'

install:
  - npm install -g bower grunt-cli jshint karma
  - npm install
  - bower install

cache:
  directories:
    - node_modules
    - bower_components

script: grunt karma distribution

after_success: ./generate-site.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_API_TOKEN
  file: angular-comics-distribution.zip
  on:
    branch: continuousintegration
